# Generated by Django 2.1 on 2020-09-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('location_type', models.CharField(choices=[('COUNTRY', 'COUNTRY'), ('CITY', 'CITY'), ('ZIP', 'ZIP')], default='CITY', max_length=10)),
                ('location', models.TextField(default='')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Contacted', 'Contacted')], default='Created', max_length=10)),
                ('communication', models.TextField(default='')),
            ],
        ),
    ]
