# Generated by Django 2.1 on 2020-09-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='communication',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
